name: mad_project_humm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  table_calendar: ^2.2.1
  intl : ^0.15.0
  date_utils: ^0.1.0+2
  flutter_clean_calendar: ^1.0.1
  carousel_slider: ^1.3.0
  image_picker : 0.6.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
